# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1caa194b9fbe2191f6c1b66ef76e72bf9ed2a8cf00a71d7f01b9f77f2c911487ad53c0b4a974e2cf098988bf31eab7975e1e10f442c9607b846e6c5a7aa0072b

test:
  secret_key_base: 0e0bc579800cc326af4da0e98fa4fc5bfc5f1f312ffdeca3a3eebed41af9b0c8d92a44bc042d6ecd41acf9f8f026b8e3fde31b0b3da95893046035661179b97a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
